= Hello & Welcome

**Hello and Welcome to the Documentation Cafe!** 

Please feel free to head over to xref:ROOT:bar.adoc[the counter], grab a drink or some food. Then kick back and peruse the xref:ROOT:library.adoc[documentation in our library].  

== What is the Documentation Cafe
The Documentation Cafe is a personal project with the following goals:

* xref:portfolio.adoc[House my technical writing portfolio]
* Practice my technical writing
* Document my interests

== House Music
The house music is by Lofi Girl, which you can listen to by clicking the video below or by opening another https://youtu.be/jfKfPfyJRdk[ browser tab here, window=blank]. Feel free to play your own music or have a quiet time. 

video::jfKfPfyJRdk[youtube]

== This Site is Built Using:
[cols="3", frame=none, grid=none] 
|===
a|* https://docs.asciidoctor.org[AsciiDoc, window=blank]
* https://docs.antora.org[Antora, window=blank]
* https://vale.sh[Vale]
a|* https://github.com[GitHub, window=blank]
* https://gitlab.com[GitLab, window=blank]
a|* https://gitlab.com/antora/antora-ui-default[Modified Antora Default Theme, window=blank]
* Linux (https://ubuntu.com/[Ubuntu, window=blank], https://pop.system76.com/[Pop!_OS, window=blank])
|===

=== Contribute
If you want to contribute to the Documentation Cafe, https://github.com/IvyCap/documentation-cafe/issues/new[submit an issue on our GitHub page].

//==== Licsense 

