= Git Quick Reference Guide

Git is a distributed version control software used for tracking change to any group of files. Git was originally developed in 2005 for use with Linux kernel development. The https://git-scm.com/[Git project] is a member project of the https://sfconservancy.org/[Software Freedom Conservancy]

== Starting a Project
=== git clone
Copy/download a repository to local machine

.HTTPS clone
----
git clone https://{serverAdress.xyz[port]/path/to/project/repoName.git}
----

.SSH Clone
----
git clone ssh://{user@serverAddress.xyz[port]:/path/to/project/repoName.git}
----

=== git clone private Github repo with MFA enabled
First you will need to obtain a Personal Access Token (PTA) from your Github account. Settings > Developer Settings > Personal access token > Fine-grained tokens. Add the token to the repo url as shown below. 

.HTTPS clone with PAT
----
git clone https://{PAT}@github.com/{userName or accountName}/{repoName.git}
----


=== git init
Create an empty git repository or reinitilezes an existing one

.git init
----
git init
----

== Git Configuration
=== git config
Set User Email and  Name

.Set global user's email
----
git config --global user.email "{emailAddress}"
----
.Set local repository user's email
----
git config --local user.email "{emailAddress}"
----
.Set global user's name
----
git config --global user.name "{usersName}"
----
.Set local repository user's name
----
git config --local user.name "{usersName}"
----

== Send Updates To or From a Repository 
=== git pull
.Pulls down latest version of remote repository and merges changes into local repository
----
git pull
----

=== git fetch 
.Downloads latest version of the remote repository without merging the changes.
----
git fetch https://{serverAdress.xyz[port]/path/to/project/repoName.git}
----

=== git push
Add changes from Committed to destination repository

.Push to original source of cloned repository
----   
git push origin
----
.Push a tag
----
git push origin {TagName}
----
.Creates and pushes branch to remote repository
----
git push --set-upstream origin {branchName}
----

== Add, and Commit Changes 
=== git add
Add changes from Unstaged to Staged

.Add changes from a direcotry
----
git add {relative/patch/to/directory}
----

.Add all files in current directory
----
git add .
----
.Add a specific file
----
git add {fileName}  
----

=== git commit

.Add changes from Staged to Committed with a note
----
git commit -m "{message}"
----

=== git reset
.Reset unstaged changes if they have not been Committed
----
git reset
----

== Branches, Commits, Tags, and Stashes Managment

=== git branch

.List branches
----
git branch
----
.Create new branch. Does not move you to the new branch.
----
git branch {branchName}
----
.Delete a branch
----
git branch -d {branchName}
----

=== git stash
.Creates a new stash and reverts to the most resent commits
----
git stash
----
.Save a stash under a name
----
git stash save "{StashName}"
----
.List stashes
----
git stash list
----
.Restore the changes from the most recent stash
----
git stash pop
----

=== git diff

.Check differences between two branches
----
git diff {Branch1} {Branch2}
----

=== git checkout
Move Head to a specific commit, branch, or tag.

.Show UUIDs for commits
----
git log
----

.Move to a specific commit
----
git checkout {UUID}
----
.Move to the master commit
----
git checkout master
----
.Check out a tags
----
git checkout {TagName}
----

.Move to a branch
----
git checkout {branchName}
----
.Create new branch and move to it.
----
git checkout -b {branchName}
----

=== git restore
----
git restore {file}
----

=== git merge

.Merges specified branch in to currently located branch
----
git merge {SourceBranch}
----
.Abort a conflicting merge
----
git merge --abort
----

=== git rebase

.Rebase(merge) current branch with SourceBranch
----
git rebase {sourceBranch}
----

=== git tag
Creates name for specific commits. Use instead of UUIDs.

.List all tags
----
git tag
----
.Add a tag with a name and message
----
git tag -a {tagName} -m "{message}"
----

== Status and History
=== git status

.Show current status of local repository
----
git status
----

=== git log

.Show history of repository name
----
git log
----
.Compact version
----
git log --oneline
----
.Show commits as a graph
----
git log --graph
----
.Show commits as a compact graph
----
git log --graph --oneline
----

== Stages
* **Unstaged** - made changes that may not be kept
* **Staged** - Made changes that you are sure you want to keep
* **Committed** - Defiantly want to keep changes
* **Pushed** - Uploaded changes to remote repository
