= Git Quick Reference Guide
:toc: right

Git is a distributed version control software used for tracking change to any group of files. Git was originally developed in 2005 for use with Linux kernel development. The https://git-scm.com/[Git project] is a member project of the https://sfconservancy.org/[Software Freedom Conservancy].

== Cloning, Pulling, Pushing, and Fetching branches and commits  
=== git clone
Copy/download repo or branch to local machine

.HTTPS clone
----
git clone https://address.com/reponame
----

.SSH Clone
----
 git clone git@github.com:IvyCap/test-repo.git
----
=== git pull
Pulls down latest version of remote repo and merges changes into local repo.
----
git pull
----

=== git fetch 
Downloads latest version of the remote repo without merging the changes.
----
git fetch http://address.com/reponame
----

=== git push
Add changes from Committed to destination repo

.push to original source of cloned repo
----   
git push origin
----
.push a tag
----
git push origin <TagName>
----
.Creates and pushes branch to remote repo
----
git push --set-upstream origin <branchName>
----

== Changing, and Setting Stages, and Commits  
=== git add

.Add changes from Unstaged to Staged
----
git add <*Source*>
----

.add all files in current directory
----
git add .
----
.add a specific file
----
git add fileName  
----

=== git commit

.Add changes from Staged to Committed with a note
----
git commit -m "message"
----

=== git checkout
To revert changes(*Move Head*) to a specific commit.

.get UUID for commit
----
git history
----
.revert to a specific commit
----
git checkout UUID
----
.revert to the master commit
----
git checkout master
----
.check out a tags
----
git checkout tags/TagName
----
.move to a branch
----
git checkout branchName
----
.create new branch and move to it.
----
git checkout -b branchName
----

=== git reset
Rest unstaged changes if they have not been Committed
----
git reset
----

== Branches and Stashes

=== git branch

.List branches
----
git branch
----
.Create new branch. Does not move you to the new branch.
----
git branch branchName
----
.delete a branch
----
git branch -d branchName
----

=== git stash
.Creates a new stash and reverts to the most resent commits
----
git stash
----
.save a stash under a name
----
git stash save "StashName"
----
.list stashes
----
git stash list
----
.restore the changes from the most recent stash
----
git stash pop
----

=== git diff

.Check differences between two branches
----
git diff <*Branch1*> <*Branch2*>
----

=== git merge

.Merges specified branch in to currently located branch
----
git merge <*SourceBranch*>
----
.abort a conflicting merge
----
git merge --abort
----

=== git rebase

.Rebase(merge) current branch with SourceBranch
----
git rebase SourceBranch
----

=== git tag
creates name for specific commits. Use instead of UUIDs.

.List all tags
----
git tag
----
.add a tag with a name and message
----
git tag -a <*TagName*> -m "Update note"
----

=== got config
Set User Email and  Name
.Set global user email
----
git config --global user.email "you@example.com"
----
.Set local repo user email
----
git config --local user.email "you@example.com"
----
.Set global user name
----
git config --global user.name "Your Name"
----
.Set local repo user name
----
git config --local user.name "Your Name"
----


== Status and History
=== git status

.Show current status of local repo
----
git status
----

=== git log

.Show history of reponame
----
git log
----
.compact version
----
git log --oneline
----
.Show commits as a graph
----
git log --graph
----
.Show commits as a compact graph
----
    git log --graph --oneline
----

== Stages
* **Unstaged** - made changes that may not be kept
* **Staged** - Made changes that you are sure you want to keep
* **Committed** - Defiantly want to keep changes
* **Pushed** -